# 행렬 곱 연산 구현

In [11]:
import numpy as np

In [12]:
x = np.array([1,2])
print(x)
x_dim = np.ndim(x)     # x행렬의 차원
x_shape = x.shape      # x행렬의 모양
print(x_dim)
print(x.shape)

[1 2]
1
(2,)


In [13]:
w = np.array([[1,3,5], [2,4,6]])
print(w)
w_dim = np.ndim(w)      # w행렬의 차원
w_shape = w.shape       # w행렬의 모양
print(w_dim)
print(w_shape)

[[1 3 5]
 [2 4 6]]
2
(2, 3)


In [14]:
y = np.dot(x,w)          # x와 w 행렬의 곱
print(y)
y_dim = np.ndim(y)       # y행렬의 차원
y_shape = y.shape        # y행렬의 모양
print(y_dim)
print(y_shape)

[ 5 11 17]
1
(3,)


# 3층 신경망 구현

In [17]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(W1.shape)
print(X.shape)
print(B1.shape)

A1 = np.dot(X, W1) + B1

print(A1)

(2, 3)
(2,)
(3,)
[0.3 0.7 1.1]


In [23]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [24]:
Z1 = sigmoid(A1)

print(Z1)

[0.57444252 0.66818777 0.75026011]


In [26]:
W2 = np.array([[0.1,0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

print(A2)
print(Z2)

(3,)
(3, 2)
(2,)
[0.51615984 1.21402696]
[0.62624937 0.7710107 ]


In [28]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = sigmoid(A3)

print(A3)
print(Y)

[0.31682708 0.69627909]
[0.57855079 0.66736228]


# 3층 신경망 코드 정리

In [32]:
import numpy as np

def sigmoid(x):      # sigmoid 함수 구현
    return 1 / (1 + np.exp(-x))

# 0->1층 신경망
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])

print(W1.shape)
print(X.shape)
print(B1.shape)

A1 = np.dot(X, W1) + B1
Z1 = sigmoid(A1)
print(A1)
print(Z1)

# 1->2층 신경망
W2 = np.array([[0.1,0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

print(A2)
print(Z2)

# 2->3층 신경망
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

A3 = np.dot(Z2, W3) + B3
Y = sigmoid(A3)

print(A3)
print(Y)          # 최종 결과값

(2, 3)
(2,)
(3,)
[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]
(3,)
(3, 2)
(2,)
[0.51615984 1.21402696]
[0.62624937 0.7710107 ]
[0.31682708 0.69627909]
[0.57855079 0.66736228]
